### ISSUE TITLE
Hands-on Introduction to Linux Commands and Shell Scripting graded quiz missing

### ISSUE THREAD

**Issue by johnfelipe** [dennislamcv1/IBMAppliedSE#2]
![SNAG-0119](https://user-images.githubusercontent.com/428820/185829532-db6eec94-b0ef-4208-b218-5f5d30dcbdad.png)
??

**Comment by dennislamcv1** [comment]
Will revisit when I am doing DevOps Final Project.

**Comment by dennislamcv1** [comment]
Close as now

**Comment by dennislamcv1** [comment]
I have completed and posted the Final Exam answers
